port: 8080
logging:
  level:
    root: INFO
  file:
    name: logs/application.log
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 2000
    cache:
      redis:
        max-memory-policy: allkeys-lru
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: /yX7Di2OZm6Zb/l8KdOnV3gs1XlSu/DXgzis0IY3QPwOA5Ow6mvYmqCOrIiGMkMjMsY3S7v6HE9pNbmC8e+okw==
  expiration: 3600000
rsa:
  public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAX1rA1XNDTbiN9cN3/cTwZOTI8+k/1HDMOtzk3GhETzqTLmZAto8hXk6lywOqJD8Bwa0onFm+YvQlPdZEEgnBa2atUyDoKsZvkgWzXrxkDQpGghPdqY1atunc1LevAjEWqIdHUgKgyTyNSzzTj7maWL2UNPiCE+LuOM0fa0owlwIDAQAB
  private: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMBfWsDVc0NNuI31w3f9xPBk5Mjz6T/UcMw63OTcaERPOpMuZkC2jyFeTqXLA6okPwHBrSicWb5i9CU91kQSCcFrZq1TIOgqxm+SBbNevGQNCkaCE92pjVq26dzUt68CMRaoh0dSAqDJPI1LPNOPuZpYvZQ0+IIT4u44zR9rSjCXAgMBAAECgYAyi9uIt40lrhJEGsNVj/RjRd9nfc9X2jYZM44/BDrRWBAIBDUR4+YP2nvHzGQWHJgBmiYpeYuLHu0PrAPUtvigyDf6GLa1R9dtjsHZmlKf/lQgDkmeQdiWj8QatpneYlzhai2MZxY4iZzniItzgLu8qIJ3Ust/0DHlslUdj3O5oQJBAP1A4DNd2Aj1Abg79G/JGvUj+juvXO5wewsDDZXminkRvbb2Etu1e8Ej0sSfT3c+f7Wr1qyyRDlxbYPmkBMo7ssCQQDCdXNwgSU0XGE2JayswvcENvUfLgYuE8T3UvDc3kUekh6fKcFyKMHYYjYS+DNWokVy2wjMFTP8jSBPLCLuBh/lAkEAnQpgvJmBwDQlp9fNwI/FHqP7pI0epGCte+udvglibqbYrJ60nPdR0TdkmDZtsXTY/o+bJCW69p/mmDcdujPUtwJAX4lgq9dnNfBk+jtMOJyYy4NMroLoGl8wF+qx13GEN97GGKBlH/cSNYMa2fsDDf8va5xdGBcasWuMghlHF/X+WQJAREt46iq8eLWoadOU/nhK4fDAGVZmM/GpibHPuC+kMil2ewaBYniiWJfG4j7cuWnf6I10oAwDmrQfJvC6opbGuA==